import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getAuthenticatedUser } from '@/lib/auth';

export const dynamic = 'force-dynamic';

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const user = await getAuthenticatedUser();
    if (!user) return NextResponse.json({ error: 'User not authenticated' }, { status: 401 });

    const course = await prisma.course.findUnique({
      where: { id: params.id },
      include: {
        subjects: {
          include: {
            chapters: {
              include: { topics: true },
            },
          },
        },
        documents: true,
      },
    });

    if (!course) return NextResponse.json({ error: 'Course not found' }, { status: 404 });

    // Generate formatted Markdown cheat sheet
    let markdown = `# 🎓 ${course.title} (${course.code || 'University Course'})\n`;
    markdown += `**Comprehensive Exam Revision Cheat Sheet & High-Yield Summary**\n`;
    markdown += `*Generated by Samap for ${user.name || 'Scholar'} on ${new Date().toLocaleDateString()}*\n\n`;
    markdown += `---\n\n`;

    course.subjects.forEach((subj, sIdx) => {
      markdown += `## Unit ${sIdx + 1}: ${subj.title}\n\n`;
      subj.chapters.forEach((chap) => {
        markdown += `### 📌 ${chap.title}\n`;
        chap.topics.forEach((top) => {
          markdown += `* **${top.title}**\n`;
          markdown += `  * *Key Definition:* Fundamental concept in ${subj.title}.\n`;
          markdown += `  * *5-Mark Exam Tip:* Include formal equations, state diagrams, and edge cases.\n`;
        });
        markdown += `\n`;
      });
    });

    markdown += `\n---\n`;
    markdown += `### 💡 Universal University Exam Strategy\n`;
    markdown += `1. **Definitions (1 Mark):** Write clear 1-2 sentence definitions with keywords underlined.\n`;
    markdown += `2. **Formulas & Conditions (2 Marks):** Explicitly state mathematical equations and boundary conditions.\n`;
    markdown += `3. **Diagrams (1-2 Marks):** Draw neat architecture or flow diagrams with clear labels.\n`;
    markdown += `4. **Complexity & Limitations (1 Mark):** Always state time/space complexity $\\mathcal{O}(\\cdot)$ and practical trade-offs.\n`;

    return NextResponse.json({
      courseTitle: course.title,
      courseCode: course.code,
      markdown,
    });
  } catch (error) {
    console.error('Error generating cheatsheet:', error);
    return NextResponse.json({ error: 'Failed to generate cheatsheet' }, { status: 500 });
  }
}
